config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  root to: 'pages#home'
  get '/:provider/initializer', to: 'providers#initializer', as: 'initializer_provider'
  get '/:provider/results', to: 'results#index', as: 'results'
  get '/:provider/connect', to: 'providers#new', as: 'new_provider'
  get '/monitor', to: 'results#monitor', as: 'monitor'

  devise_for :users

  get '/auth/:provider/callback', to: 'providers#create'

  mount ActionCable.server, at: '/cable'

  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :user
  has_many :results, dependent: :destroy
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :provider
  has_one :user, through: :provider

  scope :photos, -> { where(category: 'photo') }
  scope :texts, -> { where(category: 'post') }
  scope :videos, -> { where(category: 'video') }
  scope :pages, -> { where(category: 'page') }

end

app/models/user.rb
class User < ApplicationRecord

  has_many :providers
  has_many :results, through: :providers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :google], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :google], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def after_sign_in_path_for(resource)
    results_path("facebook")
  end

  def after_sign_up_path_for(resource)
    new_provider_path("facebook")
  end

  # def after_sign_out_path_for(resource_or_scope)
  # request.referrer
  # end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  layout 'home'

  def home

  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController



  def create
    authorize Provider
    if params[:provider] == 'facebook'
      create_or_update_for_facebook(auth_hash)
    elsif params[:provider] == 'twitter'
      create_twitter(params)
    elsif params[:provider] == 'google'
      create_google(params)
    elsif params[:provider] == 'instagram'
      create_instagram(params)
    else
      flash[:alert] = 'Provider not handled'
      return redirect_to root_path
    end
    return redirect_to results_path(params[:provider])
  end

  def create_or_update_for_facebook(hash)
    provider = Provider.create!(
        name: params[:provider],
        uid: hash[:uid],
        expires_at: hash[:credentials][:expires_at],
        token: hash[:credentials][:token],
        user: current_user
      )
    authorize provider
    FacebookJob.perform_later(provider.id)
  end

  def create_twitter(params)
    username = params["twitter_username"]
    user_id = current_user.id
    @provider = Provider.create!(
      name: "twitter",
      user: current_user,
      username: username
    )
    provider_id = @provider.id
    #TwitterJob.perform_later(username, user_id, provider_id)
  end

  def create_google(params)
    user_ip = Geocoder.search("#{request.remote_ip}").first.city
    country_code = Geocoder.search("#{request.remote_ip}").first.country_code
    user_id = current_user.id
    full_name = params["full_name"]
    provider = Provider.create!(
      name: "google",
      user: current_user
    )
    provider_id = provider.id
    GoogleJob.perform_later(full_name, user_id, user_ip, country_code, provider_id)
  end

  def create_instagram(params)
    skip_authorization
    provider = Provider.create(
        name: params[:provider],
        user: current_user
      )
    username = params[:username]
    user_id = current_user.id
    provider_id = provider.id
    InstaJob.perform_later(username, user_id, provider_id)
  end

  def new
    if params[:dr]
      a = current_user.providers.where(name: params[:provider])
      a.each do |providr|
       providr.destroy
      end
    end
    provider = Provider.new
    authorize provider
    @provider = params[:provider]
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  before_action :load_results

  def monitor
    skip_authorization
    if params["/monitor"]
      if params["/monitor"]["title"]
        flash[:notice] = 'You successfully subscribed !'
      end
    end
  end

  def index

    if @loaded_provider.nil?
      return redirect_to new_provider_path(params[:provider])
    end

    if @loaded_provider.name == "facebook"
      if @loaded_provider.expires_at <= Time.now.to_i
        current_user.providers.where(name: "facebook").destroy_all
        return redirect_to new_provider_path(params[:provider])
      end
    end

  end

  private

  def load_results
    @provider = params[:provider]
    @results = policy_scope(Result).select { |r| r.provider.name == @provider }
    @loaded_provider = Provider.where(name: params[:provider], user: current_user).last

    # check_results_size ??

    if @provider == "facebook"
      @category = params[:category]
      if params[:category] == 'photo'
        @results = @results.select { |r| r.category == "photo" }
      elsif params[:category] == 'post'
        @results = @results.select { |r| r.category == "post" }
      elsif params[:category] == 'video'
        @results = @results.select { |r| r.category == "video" }
      elsif params[:category] == 'page'
        @results = @results.select { |r| r.category == "page" }
      else
        @results
      end

      @privacy = params[:privacy]
      if params[:privacy] == 'public'
        @results = @results.select { |r| r.privacy == "EVERYONE"}
      elsif params[:privacy] == 'friends'
        @results = @results.select { |r| r.privacy == "ALL_FRIENDS"}
      elsif params[:privacy] == 'myself'
        @results = @results.select { |r| r.privacy == "SELF"}
      else
        @results
      end

    elsif @provider == "twitter"
      @category = params[:category]
      if params[:category] == 'from'
        @results = @results.select { |r| r.category == "twitter-from" }
      elsif params[:category] == 'to'
        @results = @results.select { |r| r.category == "twitter-to" }
      else
        @results
      end

    end

    @paginatable_array = Kaminari.paginate_array(@results).page(params[:page])
    @results = @paginatable_array
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'logo.png' %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

<!--     Twitter Card data
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>"> -->


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/muuri/0.5.3/muuri.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/muuri/0.5.3/muuri.min.js"></script>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'logo.png' %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

<!--     Twitter Card data
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>"> -->


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'home', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'home' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- START PRELOADER -->
  <div id="preloader">
    <div id="status">&nbsp;</div>
  </div>
  <!-- END PRELOADER -->
  <!-- Return to Top -->
  <a href="javascript:" id="return-to-top"><span class="fa fa-arrow-up" aria-hidden="true"></span></a>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://hdwallsource.com/img/2014/9/earth-pictures-23104-23754-hd-wallpapers.jpg');">
    <%= link_to(new_user_session_path) do %>
      <p class="btn btn-signup" id="log">log In</p>
    <% end %>
    <div class="banner-content">
      <div id="logo">
        <ul>
          <li>
            <%= image_tag "white-logo.png", style: "width: 60px; height: 60px;" %>
          </li>
          <li>
            <p>STALK_<span style="color: #87A1DC;">HUB</span></p>
          </li>
        </ul>
      </div>
      <h1 class="text-center" id="title">STALK_<span style="color: #87A1DC;">HUB</span></h1>
       <h4 class="intro-text">What can be found about you on <span class="txt-rotate" data-period="100" data-rotate='[ "Facebook", "Instagram", "LinkedIn", "Twitter","Google"]' style="color: #B27062"></span></h4>
      <%= link_to(new_user_registration_path) do %>
        <p class="btn btn-signup call-to-action">Discover</p>
      <% end %>
      <div class="row">
        <div class="col-xs-12">
          <div class="mouse-warp">
            <a href="#mouse-here" class="page-scroll">
              <i class="fa fa-angle-down fa-3x" style="color: #FFF;" aria-hidden="true" id="arrow"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  </header>
  <!-- end intro header -->
  <div id="mouse-here"></div>
  <!-- only for mouse to fall before the start of the section -->
    <!-- start count stats -->
    <section id="counter-stats">
      <div class="container">
        <div class="row">
          <div class="subtitle">
            <h3 class="text-center">OUR <span style="color: #B27062;">SOCIAL MEDIAS</span></h3>
          </div>
          <div class="col-md-3 col-sm-6 col-xs-12 stats">
            <span class="fa fa-facebook-square" aria-hidden="true"></span>
            <p style="padding-top: 30px;">Facebook</p>
          </div>
          <div class="col-md-3 col-sm-6 col-xs-12 stats">
            <span class="fa fa-instagram" aria-hidden="true"></span>
            <p style="padding-top: 30px;">Instagram</p>
          </div>
          <div class="col-md-3 col-sm-6 col-xs-12 stats">
            <span class="fa fa-twitter" aria-hidden="true"></span>
            <p style="padding-top: 30px;">Twitter</p>
          </div>
          <div class="col-md-3 col-sm-6 col-xs-12 stats">
            <span class="fa fa-linkedin" aria-hidden="true"></span>
            <p style="padding-top: 30px;">Linkedin</p>
          </div>
        </div>
      </div>
    </section>

  <div class="row">
    <div class="subtitle">
      <h3 class="text-center">OUR <span style="color: #B27062;">SERVICES</span></h3>
    </div>
    <div class="col-md-4 col-xs-12 stats">
      <span class="fa fa-users fa-wrapper" aria-hidden="true"></span>
      <h3>Check your public profile</h3>
      <p style= "padding-top: 30px">Did you really protect your privacy on the web ?</p>
    </div>
    <div class="col-md-4 col-xs-12 stats">
      <span class="fa fa-eye" aria-hidden="true"></span>
      <h3>Keep an eye on your social media</h3>
      <p style= "padding-top: 30px">We retrieve all informations <br> from different social platforms.</p>
    </div>
    <div class="col-md-4 col-xs-12 stats">
      <span class="fa fa-comments-o fa-wrapper" aria-hidden="true"></span>
      <h3>Posts, tweets, photos ...</h3>
      <p style= "padding-top: 30px">We check everything about you.</p>
    </div>
  </div>

  <!-- Team -->

      <div class="container">
        <div class="team">
          <div class="row">
            <div class="subtitle">
              <h3 class="text-center">OUR <span style="color: #B27062;">TEAM</span></h3>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 stats">
              <%= image_tag "lucie.jpg", class: "profil-picture"%>
              <p style= "padding-top: 30px";>Lucie Keunen</p>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 stats">
              <%= image_tag "clement.jpg", class: "profil-picture"%>
              <p style= "padding-top: 30px";>Clément Bacle</p>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 stats">
              <%= image_tag "denis.jpg", class: "profil-picture"%>
              <p style= "padding-top: 30px";>Denis Huang</p>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 stats">
              <%= image_tag "gauthier.jpg", class: "profil-picture"%>
              <p style= "padding-top: 30px";>Gauthier Vanderhaegen</p>
            </div>
          </div>
        </div>
      </div>

  <!--  --><!-- end team -->
  <!-- start footer -->
 <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    STALK_HUB
  </div>
</div>
  <!-- end footer -->

app/views/providers/new.html.erb
<div id="sidebar">
  <%= render 'shared/sidebar_menu' %>
</div>

<div id="connect-container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 ">
      <% if current_user %>
        <%= render "shared/connect_card", provider: @provider %>
      <% end %>
    </div>
  </div>
</div>

app/views/results/fb_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-2 col-xs-offset-2">

    </div>
    <div class="col-xs-6">
      <% @results.each do |result| %>
          <%= result.caption %>
          <%= result.created_at %>
          <%= link_to "GO", result.link %>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/results/index.html.erb
<div id="page">
  <div id="side_content">
    <div id="sidebar">
      <%= render 'shared/sidebar_menu', provider: @provider %>
    </div>
    <% if params[:provider] == "facebook" %>
      <div id="category_filter">
        <%= render 'shared/category_filter', provider: @provider %>
      </div>
    <% elsif params[:provider] == "twitter" %>
      <%= render 'shared/category_twitter_filter', provider: @provider %>
    <% else %>
      <div id="category_filter">
        <div class="filter-btn" id="search_again">
          <%= link_to '', new_provider_path(:dr => current_user ), class: "fa fa-search" %>
        </div>
      </div>
    <% end %>
  </div>

  <% if params[:provider] == "facebook"  %>
    <%= render 'shared/privacy_filter' %>
  <% end %>
  <div id="container-reduced">
    <div class="grid">
      <% if @results.size < 1 %>
        <div class="no-results">
          <p>There is no result at this moment</p>
        </div>
      <% else  %>
      <!-- Muuri grid -->
        <% @results.each do |result|  %>
          <div class="item">
            <div class="item-content">
              <!-- Safe zone, enter your custom markup -->
              <%= link_to result.link, target: "_blank" do %>
                <% if result.category == "google" %>
                  <%= render 'shared/google_result_card', result: result %>
                <% else %>
                  <%= render 'shared/result_card', result: result %>
                <% end %>
              <% end %>
              <!-- Safe zone ends -->
            </div>
          </div>
        <% end %>
      </div>

      <%= paginate @results, left: 1, right: 1, window: 1  %>

      <% content_for(:after_js) do %>
        <%= javascript_pack_tag 'index_results' %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/results/monitor.html.erb
<div id="sidebar">
  <%= render 'shared/sidebar_menu' %>
</div>

<div id="connect-container" class="monitor">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 ">
      <% if current_user %>
        <div class="connect_card monitor">
  <!-- icon -->
  <div class="monitor_icon">
    <i class="fa fa-eye" aria-hidden="true"></i>
    <p>Monitor your e-reputation</p>
  </div>

  <!-- name -->
      <%= simple_form_for monitor_path, method: "get" do |f| %>
        <%= f.hidden_field :title, :value => "subscribed"  %>
        <div class="checklist">
          <div class="funkyradio">
              <div class="funkyradio-success">
                  <input type="checkbox" name="checkbox1" id="checkbox3" unchecked/>
                  <label for="checkbox3">Facebook</label>
              </div>
              <div class="funkyradio-primary">
                <input type="checkbox" name="checkbox2" id="checkbox2" unchecked/>
                <label for="checkbox2">Instagram</label>
              </div>
              <div class="funkyradio-warning">
                  <input type="checkbox" name="checkbox3" id="checkbox5" unchecked/>
                  <label for="checkbox5">Twitter</label>
              </div>
              <div class="funkyradio-danger">
                <input type="checkbox" name="checkbox4" id="checkbox4" unchecked/>
                <label for="checkbox4">Web</label>
              </div>
          </div>
      <input type="submit" class="btn btn-primary" value="Subscribe !" style="margin-top:15px;"/>
    <% end %>
  </div>
<!--       <ul>
        <form action="/monitor"></form>
            <p><input id="checkBox" type="checkbox">Facebook</p>
            <p><input id="checkBox" type="checkbox">Instagram</p>
            <p><input id="checkBox" type="checkbox">Twitter</p>
            <p><input id="checkBox" type="checkbox">Web</p>
            <span><input type="submit" style="margin:0 auto"></span>
      </ul> -->
  </div>

  <!-- link -->
  <div class="link">

  </div>
</div>




      <% end %>
    </div>
  </div>
</div>

app/views/shared/_category_instagram_filter.html.erb
<div id="category_filter">
  <div class="filter-btn" id="all">
    <div>All</div>
  </div>
  <div class="filter-btn" id="reverse">
    <div>Reverse</div>
  </div>
  <div class="filter-btn">
    <%= link_to '', new_provider_path, class: "fa fa-search" %>
  </div>
</div>

app/views/shared/_category_twitter_filter.html.erb
<div id="category_filter">
  <div class="filter-btn <%= 'active' unless @category %>" id="all">
    <%= link_to results_path(@provider) do %>
      <div>All</div>
    <% end %>
  </div>
  <div class="filter-btn <%= 'active' if @category == 'from' %>" id="from">
    <%= link_to results_path(@provider, category: 'from') do %>
      <div>From me</div>
    <% end %>
  </div>
  <div class="filter-btn <%= 'active' if @category == 'to' %>" id="to">
    <%= link_to results_path(@provider, category: 'to') do %>
      <div>To me</div>
    <% end %>
  </div>
  <div class="filter-btn" id="search_again">
    <%= link_to '', new_provider_path(:dr => current_user ), class: "fa fa-search" %>
  </div>
</div>

app/views/shared/_connect_card.html.erb
<div class="connect_card">
  <!-- icon -->
  <div class="icon">
    <i class="fa fa-<%= @provider %>" aria-hidden="true"></i>
  </div>

  <!-- name -->
  <div class="name">
    <p><%= @provider %></p>
  </div>

  <!-- link -->
  <div class="link">
    <% if @provider == 'facebook' %>
      <button class="loginBtn loginBtn--facebook">
        <%= link_to 'Link my facebook account', '/auth/facebook' %>
      </button>
      <div id="status"></div>

    <% elsif @provider == 'twitter' %>
      <%= simple_form_for :provider, url: '/auth/twitter/callback', method: :get do |f| %>
        <input type="text" name="twitter_username" placeholder="Your Twitter's username" class="connect-input" >
        <input type="submit" value="Dig!" class="btn btn-default">
      <% end %>

    <% elsif @provider == 'google' %>
      <%= form_tag("/auth/google/callback", method: "get") do %>
        <%= text_field_tag(:full_name, nil, placeholder: "Your full name", class: "connect-input") %>
        <%= submit_tag("Dig!", class: "btn btn-default")%>
      <% end %>

    <% elsif @provider == 'instagram' %>
      <%= simple_form_for :provider, url: '/auth/instagram/callback', method: :get do |f| %>
        <input type="text" name="username" placeholder="Your Instagram's username" class="connect-input">
        <input type="submit" value="Dig!" class="btn btn-default">
      <% end %>

    <% else %>
      <p>Sorry, we don't handle connection to <%= @provider %> yet...</p>
    <% end %>
  </div>

  <!-- privacy policy (do not touch, or it will be disabled ;)) -->
  <div class="infos">
    <a href="//www.iubenda.com/privacy-policy/8281983" class="iubenda-white iubenda-embed" title="Privacy Policy">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "//cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- TODO: change alert so they disappear automaticaly -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_google_result_card.html.erb
<div id="result_card" class="<%= result.category %>">
  <div class="header <%= params[:provider] %>">
    <p class="username"><%= result.name  if result.name %></p>
  </div>
  <div class="content google">
      <p>
        Description : <%= result.text if result.text %>
      </p>
  </div>
</div>

app/views/shared/_muuri_result.html.erb
<div class="item">
  <div class="item-content">
    <!-- Safe zone, enter your custom markup -->
    <%= link_to result.link , target: '_blank' do %>
      <%= render 'shared/result_card', result: result %>
    <% end %>
    <!-- Safe zone ends -->
  </div>
</div>

app/views/shared/_no_connect_card.html.erb
<div class="connect_card">
  <!-- icon -->
  <div class="icon">
    <i class="fa fa-<%= @provider %>" aria-hidden="true"></i>
  </div>

  <!-- name -->
  <div class="name">
    <p><%= @provider %></p>
  </div>

  <!-- link -->
  <div class="link">

    <% if @provider == 'twitter' %>
    <p>There is no result at this moment</p>
    <%= link_to "Retry", new_provider_path %>

    <% elsif @provider == 'google' %>
    <p>There is no result at this moment</p>
    <%= link_to "Retry", new_provider_path %>


    <% elsif @provider == 'instagram' %>
    <p>There is no result at this moment</p>
    <%= link_to "Retry", new_provider_path %>

    <% else %>
      <p>Sorry, we don't handle connection to <%= @provider %> yet...</p>
    <% end %>
  </div>

  <!-- privacy policy (do not touch, or it will be disabled ;)) -->
  <div class="infos">
    <a href="//www.iubenda.com/privacy-policy/8281983" class="iubenda-white iubenda-embed" title="Privacy Policy">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "//cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
  </div>
</div>